/**
 * B2B-LAW Canonical Entity Registry (Phase 2)
 * Comprehensive Registry for all 82 business entities across SQLite (Desktop) and PostgreSQL (Web).
 * Governs serialization, export/import, sync policies, and dependency topological ordering.
 */

export interface EntityDefinition {
  canonicalName: string
  tableName: string
  primaryKey: string
  tenantKey?: string
  hasCompanyId: boolean
  dependencyOrder: number
  dependsOn: string[]
  isFinancial: boolean
  isImmutableAudit: boolean
  hasAttachments: boolean
  attachmentForeignKey?: string
  sensitiveFields?: string[]
  exportPolicy: 'tenant' | 'shared_reference' | 'system_audit' | 'exclude'
  importPolicy: 'upsert' | 'append_only' | 'staging_verified' | 'skip'
}

export const CANONICAL_ENTITY_REGISTRY: Record<string, EntityDefinition> = {
  // --- 1. Core Tenant & Access Control (Order 1-5) ---
  companies: {
    canonicalName: 'companies',
    tableName: 'companies',
    primaryKey: 'id',
    hasCompanyId: false,
    dependencyOrder: 1,
    dependsOn: [],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  firm_data: {
    canonicalName: 'firm_data',
    tableName: 'firm_data',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 2,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  settings: {
    canonicalName: 'settings',
    tableName: 'settings',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 3,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  permissions: {
    canonicalName: 'permissions',
    tableName: 'permissions',
    primaryKey: 'id',
    hasCompanyId: false,
    dependencyOrder: 4,
    dependsOn: [],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'shared_reference',
    importPolicy: 'upsert'
  },
  users: {
    canonicalName: 'users',
    tableName: 'users',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 5,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    sensitiveFields: ['password_hash', 'password', 'token', 'otp_secret'],
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  role_permissions: {
    canonicalName: 'role_permissions',
    tableName: 'role_permissions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 6,
    dependsOn: ['companies', 'permissions'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  user_permissions: {
    canonicalName: 'user_permissions',
    tableName: 'user_permissions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 7,
    dependsOn: ['users', 'permissions'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  employees: {
    canonicalName: 'employees',
    tableName: 'employees',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 8,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },

  // --- 2. Master Data Entities (Order 10-19) ---
  clients: {
    canonicalName: 'clients',
    tableName: 'clients',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 10,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  defendants: {
    canonicalName: 'defendants',
    tableName: 'defendants',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 11,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  agencies: {
    canonicalName: 'agencies',
    tableName: 'agencies',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 12,
    dependsOn: ['companies', 'clients'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  experts: {
    canonicalName: 'experts',
    tableName: 'experts',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 13,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },

  // --- 3. Cases & Litigation Domain (Order 20-30) ---
  cases: {
    canonicalName: 'cases',
    tableName: 'cases',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 20,
    dependsOn: ['companies', 'clients'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  case_parties: {
    canonicalName: 'case_parties',
    tableName: 'case_parties',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 21,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  case_assignments: {
    canonicalName: 'case_assignments',
    tableName: 'case_assignments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 22,
    dependsOn: ['cases', 'employees'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  case_actions: {
    canonicalName: 'case_actions',
    tableName: 'case_actions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 23,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  sessions: {
    canonicalName: 'sessions',
    tableName: 'sessions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 24,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  session_outcomes: {
    canonicalName: 'session_outcomes',
    tableName: 'session_outcomes',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 25,
    dependsOn: ['sessions'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  judgments: {
    canonicalName: 'judgments',
    tableName: 'judgments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 26,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  judgment_amendments: {
    canonicalName: 'judgment_amendments',
    tableName: 'judgment_amendments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 27,
    dependsOn: ['judgments'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  memoranda: {
    canonicalName: 'memoranda',
    tableName: 'memoranda',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 28,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  evidence: {
    canonicalName: 'evidence',
    tableName: 'evidence',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 29,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  communications: {
    canonicalName: 'communications',
    tableName: 'communications',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 30,
    dependsOn: ['cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },

  // --- 4. Legal Services & Engagements Domain (Order 35-45) ---
  legal_service_categories: {
    canonicalName: 'legal_service_categories',
    tableName: 'legal_service_categories',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 35,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_types: {
    canonicalName: 'legal_service_types',
    tableName: 'legal_service_types',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 36,
    dependsOn: ['legal_service_categories'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_statuses: {
    canonicalName: 'legal_service_statuses',
    tableName: 'legal_service_statuses',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 37,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_priorities: {
    canonicalName: 'legal_service_priorities',
    tableName: 'legal_service_priorities',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 38,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_engagements: {
    canonicalName: 'legal_engagements',
    tableName: 'legal_engagements',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 39,
    dependsOn: ['companies', 'clients', 'legal_service_categories', 'legal_service_types'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  consultation_service_details: {
    canonicalName: 'consultation_service_details',
    tableName: 'consultation_service_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 40,
    dependsOn: ['legal_engagements'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  litigation_service_details: {
    canonicalName: 'litigation_service_details',
    tableName: 'litigation_service_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 41,
    dependsOn: ['legal_engagements', 'cases'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_service_details: {
    canonicalName: 'contract_service_details',
    tableName: 'contract_service_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 42,
    dependsOn: ['legal_engagements'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_attachments: {
    canonicalName: 'legal_service_attachments',
    tableName: 'legal_service_attachments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 43,
    dependsOn: ['legal_engagements'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    attachmentForeignKey: 'file_asset_id',
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_notes: {
    canonicalName: 'legal_service_notes',
    tableName: 'legal_service_notes',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 44,
    dependsOn: ['legal_engagements'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  legal_service_timeline: {
    canonicalName: 'legal_service_timeline',
    tableName: 'legal_service_timeline',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 45,
    dependsOn: ['legal_engagements'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },

  // --- 5. Tasks & Workflow (Order 48-52) ---
  tasks_v2: {
    canonicalName: 'tasks_v2',
    tableName: 'tasks_v2',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 48,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  task_notifications: {
    canonicalName: 'task_notifications',
    tableName: 'task_notifications',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 49,
    dependsOn: ['tasks_v2'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  task_audit_log: {
    canonicalName: 'task_audit_log',
    tableName: 'task_audit_log',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 50,
    dependsOn: ['tasks_v2'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },

  // --- 6. Documents & File Assets (Order 53-56) ---
  file_assets: {
    canonicalName: 'file_assets',
    tableName: 'file_assets',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 53,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  documents_v2: {
    canonicalName: 'documents_v2',
    tableName: 'documents_v2',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 54,
    dependsOn: ['companies', 'file_assets'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },

  // --- 7. Finance & Accounting Domain (Order 60-72) ---
  accounts: {
    canonicalName: 'accounts',
    tableName: 'accounts',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 60,
    dependsOn: ['companies'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  client_accounts: {
    canonicalName: 'client_accounts',
    tableName: 'client_accounts',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 61,
    dependsOn: ['clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  finances: {
    canonicalName: 'finances',
    tableName: 'finances',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 62,
    dependsOn: ['accounts', 'clients'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  invoices: {
    canonicalName: 'invoices',
    tableName: 'invoices',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 63,
    dependsOn: ['clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  invoice_items: {
    canonicalName: 'invoice_items',
    tableName: 'invoice_items',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 64,
    dependsOn: ['invoices'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  vouchers: {
    canonicalName: 'vouchers',
    tableName: 'vouchers',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 65,
    dependsOn: ['accounts', 'clients'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  receivables: {
    canonicalName: 'receivables',
    tableName: 'receivables',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 66,
    dependsOn: ['clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  credit_notes: {
    canonicalName: 'credit_notes',
    tableName: 'credit_notes',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 67,
    dependsOn: ['invoices', 'clients'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  payment_schedules: {
    canonicalName: 'payment_schedules',
    tableName: 'payment_schedules',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 68,
    dependsOn: ['clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  payment_history: {
    canonicalName: 'payment_history',
    tableName: 'payment_history',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 69,
    dependsOn: ['payment_schedules'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  partners: {
    canonicalName: 'partners',
    tableName: 'partners',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 70,
    dependsOn: ['companies'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  partner_contributions: {
    canonicalName: 'partner_contributions',
    tableName: 'partner_contributions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 71,
    dependsOn: ['partners'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  office_expenses: {
    canonicalName: 'office_expenses',
    tableName: 'office_expenses',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 72,
    dependsOn: ['companies'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  office_budgets: {
    canonicalName: 'office_budgets',
    tableName: 'office_budgets',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 73,
    dependsOn: ['companies'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  profit_distributions: {
    canonicalName: 'profit_distributions',
    tableName: 'profit_distributions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 74,
    dependsOn: ['partners'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },

  // --- 8. Contracts & Templates Domain (Order 75-84) ---
  contracts: {
    canonicalName: 'contracts',
    tableName: 'contracts',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 75,
    dependsOn: ['companies', 'clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_templates: {
    canonicalName: 'contract_templates',
    tableName: 'contract_templates',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 76,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_party_types: {
    canonicalName: 'contract_party_types',
    tableName: 'contract_party_types',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 77,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_parties: {
    canonicalName: 'contract_parties',
    tableName: 'contract_parties',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 78,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_participants: {
    canonicalName: 'contract_participants',
    tableName: 'contract_participants',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 79,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_signatures: {
    canonicalName: 'contract_signatures',
    tableName: 'contract_signatures',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 80,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  contract_schedules: {
    canonicalName: 'contract_schedules',
    tableName: 'contract_schedules',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 81,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_links: {
    canonicalName: 'contract_links',
    tableName: 'contract_links',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 82,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_amendments: {
    canonicalName: 'contract_amendments',
    tableName: 'contract_amendments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 83,
    dependsOn: ['contracts'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  contract_party_audits: {
    canonicalName: 'contract_party_audits',
    tableName: 'contract_party_audits',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 84,
    dependsOn: ['contract_parties'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },

  // --- 9. Enforcement & Collections Domain (Order 85-96) ---
  enforcement_files: {
    canonicalName: 'enforcement_files',
    tableName: 'enforcement_files',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 85,
    dependsOn: ['companies', 'clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enforcement_parties: {
    canonicalName: 'enforcement_parties',
    tableName: 'enforcement_parties',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 86,
    dependsOn: ['enforcement_files'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enforcement_actions: {
    canonicalName: 'enforcement_actions',
    tableName: 'enforcement_actions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 87,
    dependsOn: ['enforcement_files'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enforcement_requests: {
    canonicalName: 'enforcement_requests',
    tableName: 'enforcement_requests',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 88,
    dependsOn: ['enforcement_files'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_financial_details: {
    canonicalName: 'enf_financial_details',
    tableName: 'enf_financial_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 89,
    dependsOn: ['enforcement_requests'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_personal_details: {
    canonicalName: 'enf_personal_details',
    tableName: 'enf_personal_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 90,
    dependsOn: ['enforcement_requests'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_direct_details: {
    canonicalName: 'enf_direct_details',
    tableName: 'enf_direct_details',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 91,
    dependsOn: ['enforcement_requests'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_attachments: {
    canonicalName: 'enf_attachments',
    tableName: 'enf_attachments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 92,
    dependsOn: ['enforcement_requests'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    attachmentForeignKey: 'file_asset_id',
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_decisions: {
    canonicalName: 'enf_decisions',
    tableName: 'enf_decisions',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 93,
    dependsOn: ['enforcement_requests'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  enf_request_parties: {
    canonicalName: 'enf_request_parties',
    tableName: 'enf_request_parties',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 94,
    dependsOn: ['enforcement_requests'],
    isFinancial: false,
    isImmutableAudit: false,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  collections_claims: {
    canonicalName: 'collections_claims',
    tableName: 'collections_claims',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 95,
    dependsOn: ['companies', 'clients'],
    isFinancial: true,
    isImmutableAudit: false,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'upsert'
  },
  collections_payments: {
    canonicalName: 'collections_payments',
    tableName: 'collections_payments',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 96,
    dependsOn: ['collections_claims'],
    isFinancial: true,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },

  // --- 10. Audit, Logs & Operational Metadata (Order 97-100) ---
  activity_logs: {
    canonicalName: 'activity_logs',
    tableName: 'activity_logs',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 97,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  assignment_logs: {
    canonicalName: 'assignment_logs',
    tableName: 'assignment_logs',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 98,
    dependsOn: ['cases', 'employees'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  professional_liability_logs: {
    canonicalName: 'professional_liability_logs',
    tableName: 'professional_liability_logs',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 99,
    dependsOn: ['companies'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: true,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  },
  time_logs: {
    canonicalName: 'time_logs',
    tableName: 'time_logs',
    primaryKey: 'id',
    tenantKey: 'company_id',
    hasCompanyId: true,
    dependencyOrder: 100,
    dependsOn: ['companies', 'users'],
    isFinancial: false,
    isImmutableAudit: true,
    hasAttachments: false,
    exportPolicy: 'tenant',
    importPolicy: 'append_only'
  }
}

/**
 * Returns all entities topologically sorted by dependency order.
 */
export function getTopologicallySortedEntities(): EntityDefinition[] {
  return Object.values(CANONICAL_ENTITY_REGISTRY).sort(
    (a, b) => a.dependencyOrder - b.dependencyOrder
  )
}

/**
 * Returns all entity names permitted for tenant export/import.
 */
export function getExportableTenantEntities(): EntityDefinition[] {
  return Object.values(CANONICAL_ENTITY_REGISTRY).filter(
    (e) => e.exportPolicy === 'tenant'
  )
}
